<?php

require_once __DIR__ . '/includes/relais.inc';
/**
 * Implements hook_block_info().
 */
function relais_block_info() {
  $blocks = array();
  $blocks['relais_menu'] = array(
    'info' => t('Relais Berthet Menu'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function relais_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'relais_menu':
      $block['content'] = relais_prepare_relais_menu();
      break;
  }

  return $block;
}

/**
 * Implements hook_menu().
 */
function relais_theme() {
  $themes = array();
  $path = drupal_get_path('module', 'relais');

  $themes['main_relais_menu'] = array(
    'template' => 'relais_menu',
    'variables' => array(),
    'type' => 'theme',
    'path' => $path . '/templates',
  );

  return $themes;
}
